---

- name: Clone dotfiles repository
  tags: setup_root_home
  no_log: true
  become: true
  ansible.builtin.git:
    repo: "{{ root_home_repo }}"
    dest: "{{ root_home_dst }}"
    clone: true
    update: true
    single_branch: true
    version: "{{ root_home_repo_branch }}"

- name: Check if repo already set up
  tags: setup_root_home
  become: true
  register: check_setup_home
  changed_when: check_setup_home.rc != 0
  failed_when: check_setup_home.rc > 255
  ansible.builtin.command: "grep -w 'dotfiles/.bashrc' /root/.bashrc"

- name: Run setup script
  tags: setup_root_home
  become: true
  when: check_setup_home.rc != 0
  changed_when: check_setup_home.rc != 0
  ansible.builtin.command: "{{ root_home_dst }}/bin/setup_dotfiles_config"

...
