---

- name: Create Ansible user
  tags:
    - setup_ansible_environment
    - setup_ansible_environment_add_user
  become: true
  ansible.builtin.user:
    name: "{{ remote_ansible_username }}"
    comment: "Ansible user"
    uid: "{{ remote_ansible_uid }}"
    password: "{{ remote_ansible_password }}"
    home: "{{ remote_ansible_home }}"
    shell: "{{ remote_ansible_shell }}"
    expires: -1
    state: present

- name: Add public key to authorized_key file
  tags:
    - setup_ansible_environment
    - setup_ansible_environment_add_sshkey
  become: true
  when: remote_ansible_ssh_pub
  ansible.posix.authorized_key:
    user: "{{ remote_ansible_username }}"
    state: present
    key: "{{ remote_ansible_ssh_pub }}"

- name: Make sure sudo package is installed
  tags:
    - setup_ansible_environment
    - setup_ansible_environment_install_sudo_pkg
    - setup_ansible_environment_deploy_sudoers
  become: true
  ansible.builtin.package:
    name: sudo
    state: present

- name: Deploy ansible_sudoers configuration
  tags:
    - setup_ansible_environment
    - setup_ansible_environment_deploy_sudoers
  become: true
  ansible.builtin.template:
    src: "templates/etc/sudoers.d/ansible_sudoers.j2"
    dest: "/etc/sudoers.d/ansible_sudoers"
    owner: root
    group: root
    mode: "0640"
    backup: true
    validate: visudo -cf %s

- name: Fix ansible_remote_tmp ownership
  tags:
    - setup_ansible_environment
    - setup_ansible_environment_fix_ownership
  become: true
  when: ansible_remote_tmp is defined
  ansible.builtin.file:
    dest: "{{ ansible_remote_tmp }}"
    owner: "{{ remote_ansible_username }}"
    group: "{{ remote_ansible_username }}"
    recurse: true

...
